memories:
  - '&eThank you buat kalian yang udah mau main di server ini'
  - '&ebahkan setelah pandemi &7(meskipun yang main cuma sedikit)&e.'
  - '&bAku juga senang bisa punya pengalaman jadi developer'
  - '&bkayak gini. &aBisa ketemu player-player yang unik &a&o(meskipun'
  - '&a&oagak ngeselin :v). &fDan ga nyangka bisa ketemu beberapa'
  - '&cYou&fTuber &eatau bahkan &bV&dTuber &f&o(hehe).'
  - ''
  - '&3Ga kerasa ya udah dari &5Akhir 2019 &e- &2Pertengahan 2023'
  - '&3awalnya dari main minecraft sebagai player biasa, sekarang'
  - '&3jadi &edeveloper &3wkwkwk. &4Hampir &c4 tahun &4loh &cGG!!!'
  - ''
  - '&6Meskipun begitu, ada &cpertemuan &6pasti ada &eperpisahan.'
  - '&9Jadi, aku juga minta maaf kalo ada salah. &dGak lupa aku juga'
  - '&ducapin terima kasih buat para staff yang sudah meluangkan'
  - '&dwaktunya untuk menjaga server ini. &b&oThank you so much guys'
  - '&b&oyou guys are so cool.'
  - ''
  - '&e&lSekali lagi! &bAku ucapin banyak-banyak terima kasih buat'
  - '&bkalian semua, &apara staff dan juga member yang udah'
  - '&asupport aku dan &o(yang terpenting) &aserver ini.'
  - ''
  - '&e&lGw &b&lARVIN&a&l3108 &f&lmohon pamit undur diri. &d&lBye Bye!!!'
  - '&7&oCatatan ini diketik pada tanggal &f&o15 Juli 2023'
  - ''