name: Java CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!*.yml'
      - '!*.md'
      - '!.github/**'
      - '!.gitignore'

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Apply patches
        shell: cmd
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git config sfaloader.setup
          patchTools patch --all

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn install