on:
  push:
    branches:
      - master
    paths:
      - '!.github/**'

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Apply patches
        shell: pwsh
        run: scripts/applyPatches.ps1

      - name: Build with Maven
        run: mvn install