name: Java CI

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!*.md'
      - '!/.github/**'

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Apply patches
        shell: cmd
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          build.cmd

      - name: Build with Maven
        run: mvn install